services:
  mysqldb:
    container_name: mariadbcontainer
    image: mariadb
    restart: 'unless-stopped'
    volumes: 
      # - $HOME/database:/var/lib/mysql/
      - ./databasevolume:/var/lib/mysql/
      - ./database/db/initdb/:/docker-entrypoint-initdb.d
      # - ./databasevol:/config
      # - ./database/db/initdb/:/config/initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet
    ports:
      - 3306:3306
    expose:
      - 3306

  nodeappweb:
    container_name: nodewebcontainer
    build: ./nodejswebapi/.
    image: nodewebapp:v1
    restart: 'unless-stopped'
    volumes:
      # - $HOME/nodeappweb:/code
      - ./nodewebvol:/code
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'devchon'
      DB_PASSWORD: 'devchon101'
      DB_NAME: mymariaDB
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappwebservice
      SERVER_PORT: 3000
    depends_on:
    - mysqldb
    networks:
      - internalnet

  nodeappmobile:
    container_name: nodemobilecontainer
    build: ./nodejsmobileapi/.
    image: nodemobileapp:v1
    restart: 'unless-stopped'
    volumes:
      # - $HOME/nodeappweb:/code
      - ./nodemobilevol:/code
    ports:
      - 3001:3001
    expose:
      - 3001
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'devchon'
      DB_PASSWORD: 'devchon101'
      DB_NAME: mymariaDB
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappmobileservice
      SERVER_PORT: 3001
    depends_on:
      - mysqldb
    networks:
      - internalnet

  nodeappimage:
    container_name: nodeimagecontainer
    build: ./nodejsimageapi/.
    image: nodeimageapp:v1
    restart: 'unless-stopped'
    volumes:
      # - $HOME/nodeimagevol:/code
      # - $HOME/nodeimagevol/image:/code/src/image/
      - ./nodeimagevolume/image:/usr/code/src/image/
    ports:
      - 3002:3002
    expose:
      - 3002
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'devchon'
      DB_PASSWORD: 'devchon101'
      DB_NAME: mymariaDB
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappimageservice
      SERVER_PORT: 3002
    depends_on:
      - mysqldb
    networks:
      - internalnet

  modelapp:
    container_name: modelapicontainer
    restart: 'unless-stopped'
    build: ./modelapi/.
    ports:
      - "3004:3004"
    volumes:
      # - $HOME/modelapi:/modelapi/src/
      - ./modelapivol:/modelapi/src/
    networks:
      - webproxy

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - internalnet
    environment:
        PMA_HOST: mysqldb
        TZ: Asia/Bangkok
    depends_on:
        - mysqldb

networks:
  internalnet:
    driver: bridge
  webproxy:
    driver: bridge
